version: "3.9"
services:
  student-agent:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./credentials:/app/credentials:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
